name = "logistic"
uuid = "22f78bbb-bd7d-4783-b207-88e8f26ec866"
authors = ["natsuki <natsuki.okada77@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
